project:
  type: website
  output-dir: docs
website:
  title: "I Am Become Jeff"
  favicon: favicon.png
  navbar:
    pinned: true
    right:
      - text: "About"
        href: about.qmd
      - text: "GU Homepage<i class='bi bi-box-arrow-up-right ps-2'></i>"
        #icon: box-arrow-up-right
        href: "https://jpj.georgetown.domains"
execute: 
  warning: false
format: 
  html:
    toc: true
    mainfont: "Karmina"
    theme:
      light: default
      dark: darkly
    css: styles.css
    include-in-header:
      text: "<link rel='preconnect' href='https://fonts.googleapis.com'><link rel='preconnect' href='https://fonts.gstatic.com' crossorigin><link href='https://fonts.googleapis.com/css2?family=Reenie+Beanie&display=swap' rel='stylesheet'>"
